INSERT INTO `cyber_itemdata` (`id`, `name`, `description`, `max`) VALUES
	(1, 'cash', 'Cash money, spend it however you want.', 9999999999999999),
	(2, 'WEAPON_ADVANCEDRIFLE', 'Advanced rifle, very useful for long distances.', 1),
	(3, 'WEAPON_APPISTOL', 'The AP pistol is an automatic machine gun that acts like a 9mm pistol.', 1),
	(4, 'WEAPON_ASSAULTRIFLE', 'An assault rifle is a rifle designed for combat, selective fire.', 1),
	(5, 'WEAPON_ASSAULTSHOTGUN', 'A very powerful assault shotgun, it differs from the rest by its cylindrical magazine.', 1),	
	(6, 'WEAPON_ASSAULTSMG', 'Short and medium distance weapon, very powerful and with a fast burst.', 1),
	(7, 'WEAPON_AUTOSHOTGUN', 'Automatic shotgun, very useful.', 1),
	(8, 'WEAPON_BALL', 'A pet could play with this, it looks like fun.', 1),
	(9, 'WEAPON_BAT', 'A simple baseball bat, can you think of what to use it with?', 1),
	(10, 'WEAPON_BATTLEAXE', 'Battle ax, a bit old-fashioned...', 1),
	(11, 'WEAPON_BOTTLE', 'A bottle of Nuka-Cola, reminds me of another video game...', 1),
	(12, 'WEAPON_BULLPUPRIFLE', 'The primary benefit of a bullpup weapon is that the weapons overall length can be significantly decreased without reducing the barrel length.', 1),
	(13, 'WEAPON_BULLPUPSHOTGUN', 'The term bullpup refers to a firearm format, in which the mechanisms and the magazine are located behind the trigger.', 1),
	(14, 'WEAPON_BZGAS', 'It could be used for a police raid, take care that there are no children around.', 1),
	(15, 'WEAPON_CARBINERIFLE', 'Automatic tactical rifle, super powerful burst, try it with some accessories.', 1),
	(16, 'WEAPON_COMBATMG', 'Be careful with that, it is heavy and very powerful.', 1),
	(17, 'WEAPON_COMBATPDW', 'It looks futuristic, but it is a very good weapon.', 1),
	(18, 'WEAPON_COMBATPISTOL', 'Very good combat pistol to have a discreet weapon in your pockets.', 1),
	(19, 'WEAPON_COMPACTLAUNCHER', 'A pet could play with this, it looks like fun.', 1),
	(20, 'WEAPON_COMPACTLAUNCHER', 'Sawn-off shotgun, looks homemade, how will it work?', 1),
	(21, 'WEAPON_COMPACTRIFLE', 'Compact rifle, looks powerful.', 1),
	(22, 'WEAPON_CROWBAR', 'You can possibly force something with this.', 1),
	(23, 'WEAPON_DAGGER', 'A simple dagger, it seems quite sharp, be careful.', 1),
	(24, 'WEAPON_DBSHOTGUN', 'Double-barreled shotgun, short range, but plenty of power, believe me.', 1),
	(25, 'WEAPON_DIGISCANNER', 'What is this supposed to be?', 1),
	(26, 'WEAPON_DOUBLEACTION', 'Wow, it looks like its gold plated.', 1),
	(27, 'WEAPON_FIREEXTINGUISHER', 'Be careful, do not extinguish the flames of his heart.', 1),
	(28, 'WEAPON_FIREWORK', 'Hey hey... watch that bro.', 1),
	(29, 'WEAPON_FLARE', 'I dont know what this is, but it looks nice, doesnt it?', 1),
	(30, 'WEAPON_FLAREGUN', 'If you get lost at sea, you can use it to be rescued.', 1),
	(31, 'WEAPON_FLASHLIGHT', 'Be careful, you can make someone blind.', 1),
	(32, 'WEAPON_GARBAGEBAG', 'It smells bad, please drop it.', 1),
	(33, 'WEAPON_GOLFCLUB', 'It seems to be signed by a famous person, keep it well, it looks beautiful.', 1),
	(34, 'WEAPON_GRENADE', 'Keep that to yourself or do you want to kill us all?', 1),
	(35, 'WEAPON_GRENADELAUNCHER', 'Where did you get that? Its very dangerous brother.', 1),
	(36, 'WEAPON_GUSENBERG', 'I think I saw an equal in Scarface, very cool.', 1),
	(37, 'WEAPON_HAMMER', 'It seems to be very worn.', 1),
	(38, 'WEAPON_HANDCUFFS', 'Keep the key, if not you will not be able to release your prisoner.', 1),
	(39, 'WEAPON_HATCHET', 'The trees will tremble before you.', 1),
	(40, 'WEAPON_HEAVYPISTOL', 'Worthy of a good thief.', 1),
	(41, 'WEAPON_HEAVYSHOTGUN', 'Very good weapon, you should be careful when you use it, it looks very aggressive.', 1),
	(42, 'WEAPON_HEAVYSNIPER', 'One shot, one death.', 1),
	(43, 'WEAPON_HOMINGLAUNCHER', 'Ok, this got serious...', 1),
	(44, 'WEAPON_KNIFE', 'I dont know if you want to peel your grandfathers oranges or kill a person...', 1),
	(45, 'WEAPON_KNUCKLE', 'Cute brass knuckles, you should feel like One Punch Man.', 1),
	(46, 'WEAPON_MACHETE', 'You could use to butcher someone, or simply to cut the meat from your grill.', 1),
	(47, 'WEAPON_MACHINEPISTOL', 'Super powerful burst pistol.', 1),
	(48, 'WEAPON_MARKSMANPISTOL', 'You look like Jack Sparrow haha.', 1),
	(49, 'WEAPON_MARKSMANRIFLE', 'A lightweight sniper, very comfortable indeed.', 1),
	(50, 'WEAPON_MG', 'What kind of mess can we make with this?', 1),
	(51, 'WEAPON_MICROSMG', 'It looks small but has such a fast burst, youll be amazed when you try it.', 1),
	(52, 'WEAPON_MINIGUN', 'Classic minigun, you could use on a motorcycle or a car.', 1),
	(53, 'WEAPON_MINISMG', 'You could use on a motorcycle or a car.', 1),
	(54, 'WEAPON_MOLOTOV', 'Were going to burn down the whole city with this.', 1),
	(55, 'WEAPON_MUSKET', 'A relic of the world war.', 1),
	(56, 'WEAPON_NIGHTSTICK', 'Stop there vermin, authority is coming.', 1),
	(57, 'WEAPON_PETROLCAN', 'A very powerful smelly bottle.', 1),
	(58, 'WEAPON_PIPEBOMB', 'We could rob a bank with this.', 1),
	(59, 'WEAPON_PISTOL', 'Simple pistol, it is simple but very good for short fights or just to defend yourself.', 1),
	(60, 'WEAPON_PISTOL50', 'Simple pistol, it is simple but very good for short fights or just to defend yourself.', 1),
	(61, 'WEAPON_POOLCUE', 'Are you going to play pool?', 1),
	(62, 'WEAPON_PROXMINE', 'Proximity bomb, wouldnt you like to rob a bank with it?', 1),
	(63, 'WEAPON_PUMPSHOTGUN', 'Classic shotgun pump, it sure sounds like Fortnite haha.', 1),
	(64, 'WEAPON_RAILGUN', 'Wont you be the new admin?', 1),
	(65, 'WEAPON_REVOLVER', 'Drum revolver, like the wild west.', 1),
	(66, 'WEAPON_RPG', 'It is definitely not kid friendly.', 1),
	(67, 'WEAPON_SAWNOFFSHOTGUN', 'Police shotgun, very powerful indeed.', 1),
	(68, 'WEAPON_SMOKEGRENADE', 'Smoke grenade, if you were a magician, you would look great haha.', 1),
	(69, 'WEAPON_SNIPERRIFLE', 'A powerful sniper rifle, one shot, one kill.', 1),
	(70, 'WEAPON_SNOWBALL', 'Merry Christmas!', 50),
	(71, 'WEAPON_SNSPISTOL', 'Powerful pistol, be careful with it.', 1),
	(72, 'WEAPON_SPECIALCARBINE', 'Special carbine, mostly used by police or military.', 1),
	(73, 'WEAPON_STICKYBOMB', 'Are you going to rob a bank, or what?', 1),
	(74, 'WEAPON_STINGER', 'Hey hey, be careful brother.', 1),
	(75, 'WEAPON_STUNGUN', 'Stun gun, it doesnt do much damage, but I assure you it will hurt.', 1),
	(76, 'WEAPON_SWITCHBLADE', 'A pet could play with this, it looks like fun.', 1),
	(77, 'WEAPON_SWITCHBLADE', 'You look like a grandmothers thief, get yourself a real gun.', 1),
	(78, 'WEAPON_VINTAGEPISTOL', 'Old pistol, it belonged to Hitlers cousin, it has a lot of history.', 1),
	(79, 'WEAPON_WRENCH', 'Mechanics use it a lot.', 50),
	(80, 'cigarett', 'Smoking is bad, be careful, your lungs are having a hard time.', 50),
	(81, 'beer', 'A good beer is not denied to anyone, that you enjoy it.', 50),
	(82, 'lighter', 'A cute Zippo brand lighter.', 50),
	(83, 'chips', 'French fries, succulent.', 50),
	(84, 'chocolate', 'A rich dark chocolate.', 50),
	(85, 'cupcake', 'Who does not want a cupcake?', 50),
	(86, 'coffee', 'A delicious coffee.', 50),
	(87, 'milk', 'Milk is good for your bones, drink it.', 50),
	(88, 'cocacola', 'A good refreshment for a hot day.', 50),
	(89, 'phone', 'Cyber ​​brand phone.', 50),
	(90, 'bread', 'It looks rich and healthy.', 50),
	(91, 'water', 'There is nothing more refreshing than a bottle of water.', 1),
	(92, 'bag', 'Puedes equiparte usando /bagon.', 1),
	(93, 'cyber_ammo_pistol', 'Bullet cartridge.', 50),
	(94, 'cyber_ammo_pistol_large', 'Bullet cartridge.', 50),
	(95, 'cyber_ammo_rifle', 'Bullet cartridge.', 50),
	(96, 'cyber_ammo_rifle_large', 'Bullet cartridge.', 50),
	(97, 'cyber_ammo_shotgun', 'Bullet cartridge.', 50),
	(98, 'cyber_ammo_shotgun_large', 'Bullet cartridge.', 50),
	(99, 'cyber_ammo_smg', 'Bullet cartridge.', 50),
	(100, 'cyber_ammo_smg_large', 'Bullet cartridge.', 50),
	(101, 'cyber_ammo_snp', 'Bullet cartridge.', 50),
	(102, 'extended', 'Component for weapons.', 50),
	(103, 'light', 'Component for weapons.', 50),
	(104, 'sight', 'Component for weapons.', 50),
	(105, 'grip', 'Component for weapons.', 50),
	(106, 'goldtint', 'Component for weapons.', 50),
	(107, 'suppressor', 'Component for weapons.', 50),
	(108, 'bulletproof', 'It could save you when you least expect it.', 50);